AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

#-------------------------------------------------------------------------------
# Project standards
#-------------------------------------------------------------------------------
StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: leading
  Enabled: true

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-i'

Style/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: true

Lint/LiteralInInterpolation:
  Description: 'Avoid interpolating literals in strings'
  AutoCorrect: true

Metrics/LineLength:
  Max: 120
